from __future__ import annotations

from typing import Any


TOOL_ID_ALIASES: dict[str, str] = {
    "code.find": "code.search_text",
    "code.find_text": "code.search_text",
    "code.grep": "code.search_text",
    "code.search": "code.search_text",
    "code.search_code": "code.search_text",
    "code.search_files": "code.search_text",
    "code.list_files": "code.list_project_files",
    "code.list_project": "code.list_project_files",
    "code.project_files": "code.list_project_files",
    "code.replace": "code.replace_text",
    "code.edit": "code.edit_file",
    "code.patch": "code.apply_patch",
    "document.docx_outline": "document.extract_docx_outline",
    "document.extract_docx": "document.extract_docx_outline",
    "document.extract_word": "document.extract_docx_outline",
    "document.read_docx": "document.extract_docx_outline",
    "document.read_word": "document.extract_docx_outline",
    "document.extract_pdf": "document.extract_pdf_text_preview",
    "document.extract_pdf_text": "document.extract_pdf_text_preview",
    "document.extract_pdf_to_word": "document.extract_pdf_to_docx",
    "document.pdf_extract": "document.extract_pdf_text_preview",
    "document.pdf_extract_text": "document.extract_pdf_text_preview",
    "document.pdf_text": "document.extract_pdf_text_preview",
    "document.pdf_to_docx": "document.extract_pdf_to_docx",
    "document.pdf_to_word": "document.extract_pdf_to_docx",
    "document.read_pdf": "document.extract_pdf_text_preview",
    "document.convert_pdf_to_docx": "document.extract_pdf_to_docx",
    "document.convert_pdf_to_word": "document.extract_pdf_to_docx",
    "document.translate_word": "document.translate_docx",
    "document.translate_document": "document.translate_docx",
    "document.translate_to_chinese": "document.translate_docx",
    "document.docx_translate": "document.translate_docx",
    "document.export_md": "document.export_markdown",
    "document.markdown_export": "document.export_markdown",
    "document.export_word": "document.export_docx",
    "document.create_docx": "document.generate_docx_from_outline",
    "document.generate_docx": "document.generate_docx_from_outline",
    "document.generate_powerpoint": "document.generate_ppt",
    "document.create_ppt": "document.generate_ppt",
    "document.export_ppt": "document.generate_ppt",
    "document.merge_pdf": "document.merge_pdfs",
    "document.pdf_merge": "document.merge_pdfs",
    "document.split_pdfs": "document.split_pdf",
    "document.pdf_split": "document.split_pdf",
    "document.bookmark_outline": "document.create_bookmark_outline",
    "document.create_pdf_bookmarks": "document.create_bookmark_outline",
    "filesystem.list": "filesystem.scan_folder",
    "filesystem.list_dir": "filesystem.scan_folder",
    "filesystem.list_directory": "filesystem.scan_folder",
    "filesystem.list_files": "filesystem.scan_folder",
    "filesystem.list_project_files": "code.list_project_files",
    "filesystem.listdir": "filesystem.scan_folder",
    "filesystem.ls": "filesystem.scan_folder",
    "filesystem.scan": "filesystem.scan_folder",
    "filesystem.read": "filesystem.read_file",
    "filesystem.read_text": "filesystem.read_file",
    "filesystem.preview": "filesystem.read_text_preview",
    "filesystem.preview_text": "filesystem.read_text_preview",
    "filesystem.read_preview": "filesystem.read_text_preview",
    "filesystem.write": "filesystem.write_file",
    "filesystem.write_text": "filesystem.write_file",
    "filesystem.write_temp": "filesystem.write_temp_file",
    "filesystem.write_temporary_file": "filesystem.write_temp_file",
    "filesystem.create_temp_file": "filesystem.write_temp_file",
    "filesystem.temp_write": "filesystem.write_temp_file",
    "git.get_status": "git.status",
    "git.show_status": "git.status",
    "git.get_diff": "git.diff",
    "git.show_diff": "git.diff",
    "git.history": "git.log",
    "git.show_log": "git.log",
    "git.commit_changes": "git.commit",
    "memory.remember": "memory.save",
    "memory.search": "memory.recall",
    "memory.retrieve": "memory.recall",
    "shell.command": "shell.run_command",
    "shell.exec": "shell.run_command",
    "shell.execute": "shell.run_command",
    "shell.run": "shell.run_command",
    "web.fetch": "web.fetch_url",
    "web.get_url": "web.fetch_url",
    "web.read_url": "web.extract_text",
    "web.scrape": "web.extract_text",
    "web.render": "web.render_page",
}


def normalize_tool_syntax(value: Any) -> str:
    return str(value or "").strip().replace("__", ".")


def normalize_tool_id(value: Any) -> str:
    tool_id = normalize_tool_syntax(value)
    return TOOL_ID_ALIASES.get(tool_id, tool_id)
