[package]
name = "yuntaocode"
version = "0.1.0"
description = "YuntaoCode desktop shell"
authors = ["沈阳云涛智能科技有限公司 <wutaoplay@outlook.com>"]
license = "Apache-2.0"
repository = "https://github.com/yuntaozn/YuntaoCode"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "yuntaocode_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
